apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.clusterName }}
spec:
  version: {{ .Values.version }}
  http:
    service:
      metadata:
        annotations:
          {{- if .Values.http.psc.enabled }}
          networking.gke.io/load-balancer-type: "Internal"
          networking.gke.io/internal-load-balancer-subnet: {{ .Values.http.psc.subnet | quote }}
          {{- end }}
      spec:
        type: {{ .Values.http.type }}
        {{- if not .Values.http.psc.enabled }}
        loadBalancerSourceRanges:
        {{- range .Values.http.allowedCIDRs }}
          - {{ . | quote }}
        {{- end }}
        {{- end }}
  nodeSets:
  {{- range .Values.nodeSets }}
  - name: {{ .name }}
    count: {{ .count }}
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: {{ .javaOpts | quote }}
          resources:
            requests:
              memory: {{ .resources.requests.memory }}
              cpu: {{ .resources.requests.cpu | quote }}
            limits:
              memory: {{ .resources.limits.memory }}
              cpu: {{ .resources.limits.cpu | quote }}
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .storage }}
  {{- end }}
{{- if .Values.http.psc.enabled }}
---
apiVersion: networking.gke.io/v1
kind: ServiceAttachment
metadata:
  name: {{ .Values.clusterName }}-psc
spec:
  connectionPreference: ACCEPT_MANUAL
  natSubnets:
    - {{ .Values.http.psc.natSubnet }}
  proxyProtocol: false
  resourceRef:
    kind: Service
    name: {{ .Values.clusterName }}-es-http
  consumerAllowList:
    {{- range .Values.http.psc.consumerProjectIds }}
    - project: {{ . }}
      connectionLimit: 10
    {{- end }}
{{- end }}
